services:

  postgres:
      image: postgres:16
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - pg_data_tennis:/var/lib/postgresql/data

volumes:
  pg_data_tennis: